name: Mirror Main to Test-Mirror

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Mirror Main to Test-Mirror
        id: mirror
        uses: ./ # Replace with the specific release or tag for your custom mirror action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source-branch: 'main'
          destination-branch: 'test-mirror'
    
